VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do | config |
	config.vm.box = "ubuntu/trusty64"
	config.vm.define "control" do | control |
		control.vm.network :private_network, ip: "10.30.0.40"
	end
	config.vm.define "db" do |db|
		db.vm.network :private_network, ip: "10.30.0.41"
	end
	config.vm.define "dbel" do |db|
		db.vm.network :private_network, ip: "10.30.0.42"
		db.vm.box = "centos"
		db.vm.box = "puphpet/centos65-x64"
	end
	config.vm.define "www" do |www|
		www.vm.network :private_network, ip: "10.30.0.43"
	end
	config.vm.define "lb" do |lb|
		lb.vm.network :private_network, ip: "10.30.0.44"
	end
end
